include: package:lints/recommended.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Style
    - prefer_single_quotes
    - prefer_final_locals
    - prefer_final_in_for_each
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables

    # Documentation
    - public_member_api_docs
    - package_api_docs

    # Performance
    - avoid_function_literals_in_foreach_calls
    - prefer_collection_literals
    - use_collection_literals

    # Error prone
    - avoid_catching_errors
    - avoid_empty_else
    - avoid_print
    - prefer_typing_uninitialized_variables

    # Flutter-ready (even though we're pure Dart)
    - avoid_web_libraries_in_flutter
    - use_key_in_widget_constructors