name: kotlinish
description: Kotlin-inspired extensions and utilities for Dart/Flutter - scope functions, powerful collections, elegant async, and more.
version: 0.5.0-dev
homepage: https://github.com/keelvin/kotlinish
repository: https://github.com/keelvin/kotlinish
issue_tracker: https://github.com/keelvin/kotlinish/issues
documentation: https://github.com/keelvin/kotlinish#readme

topics:
  - dart
  - flutter
  - kotlin
  - extensions
  - utilities

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: 1.26.2
  lints: 6.0.0
  coverage: 1.15.0
